/home/chadwick/ooi/ooiData.py success: 888
